name: Deploy to GitHub Pages

on:
  push:
    branches: [using-aws]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Pull the repository
      - run: bun install && bun run build # Outputs ./dist

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
