name: Deploy to GitHub Pages

on:
  push:
    branches: [using-aws]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Pull the repository
      - uses: oven-sh/setup-bun@v2.0.2 # Set up bun runtime
      - run: bun install && bun run build # Outputs ./dist

      # Deploy to GitHub Pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.4
        with:
          folder: dist
